const router = require('express').Router();
const authController = require('../controllers/authController');
const { isAuthorized } = require('../middlewares/Auth');
const demoValidation = require('../middlewares/demoValidation');
router.post('/register', demoValidation, authController.register);
router.post('/login', authController.login);
router.get('/status', demoValidation, isAuthorized, authController.isLoggedIn);
router.get('/logout', demoValidation, isAuthorized, authController.logout);
router.post('/reset_password', demoValidation, authController.sendResetPasswordEmail);
router.post('/reset_password/:token', demoValidation, authController.changePassword);
module.exports = router;
