name: 🥸 Build and deploy Rafiki to Azure Web App Service 🕵️‍♀️

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: 'production'

jobs:
  build-and-deploy:
    environment:
      name: 'Production'
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rafiki-backend1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
